// Generated by scripts/generate-adapters.js. Do not edit directly.

import Foundation

extension CliStyle {

	/**
	 * Return agent-transcript output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func agentTranscript(
		entries: [[String: Any]]? = nil,
		title: String? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"entries": entries ?? [],
		]

		if let title = title {
			data["title"] = title
		}

		return try render("agent-transcript", data: data, options: options)
	}

	/**
	 * Return audit-finding output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func auditFinding(
		result: String,
		finding: String,
		location: String = "",
		recommendation: String = "",
		evidence: String = "",
		reference: String = "",
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"result": result,
			"finding": finding,
			"location": location,
			"recommendation": recommendation,
			"evidence": evidence.isEmpty ? [] : [evidence],
			"references": reference.isEmpty ? [] : [reference],
		]

		return try render("audit-finding", data: data, options: options)
	}

	/**
	 * Return bar-chart output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func barChart(
		rows: [[String: Any]]? = nil,
		barWidth: Int? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"rows": rows ?? [],
		]

		if let barWidth = barWidth {
			data["barWidth"] = barWidth
		}

		return try render("bar-chart", data: data, options: options)
	}

	/**
	 * Return bullet-list output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func bulletList(
		items: [[String: Any]],
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"items": items,
		]

		return try render("bullet-list", data: data, options: options)
	}

	/**
	 * Return chip output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func chip(
		label: String,
		tone: String = "neutral",
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"label": label,
			"tone": tone,
		]

		return try render("chip", data: data, options: options)
	}

	/**
	 * Return command-result output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func commandResult(
		result: String,
		summary: String,
		command: String = "",
		exitCode: Int? = nil,
		duration: String = "",
		detail: String = "",
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"result": result,
			"summary": summary,
			"command": command,
			"duration": duration,
			"details": detail.isEmpty ? [] : [detail],
		]

		if let exitCode = exitCode {
			data["exitCode"] = exitCode
		}

		return try render("command-result", data: data, options: options)
	}

	/**
	 * Return compact-data-table output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func compactDataTable(
		columns: [[String: Any]],
		rows: [[String: Any]],
		summary: String = "",
		title: String? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"columns": columns,
			"rows": rows,
			"summary": summary,
		]

		if let title = title {
			data["title"] = title
		}

		return try render("compact-data-table", data: data, options: options)
	}

	/**
	 * Return confirmation-result output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func confirmationResult(
		state: String,
		action: String,
		item: String = "",
		detail: String = "",
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"state": state,
			"action": action,
			"item": item,
			"detail": detail,
		]

		return try render("confirmation-result", data: data, options: options)
	}

	/**
	 * Return diagnostic-report output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func diagnosticReport(
		title: String? = nil,
		checks: [[String: Any]]? = nil,
		findings: [[String: Any]]? = nil,
		skippedChecks: [[String: Any]]? = nil,
		nextActions: [String]? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"checks": checks ?? [],
			"findings": findings ?? [],
			"skippedChecks": skippedChecks ?? [],
			"nextActions": nextActions ?? [],
		]

		if let title = title {
			data["title"] = title
		}

		return try render("diagnostic-report", data: data, options: options)
	}

	/**
	 * Return diff-block output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func diffBlock(
		lines: [[String: Any]]? = nil,
		path: String = "",
		title: String? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"path": path,
		]

		if let lines = lines {
			data["lines"] = lines
		}
		if let title = title {
			data["title"] = title
		}

		return try render("diff-block", data: data, options: options)
	}

	/**
	 * Return divider output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func divider(
		label: String = "",
		dividerWidth: Int? = nil,
		dividerColour: String? = nil,
		labelColour: String? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"label": label,
		]

		if let dividerWidth = dividerWidth {
			data["dividerWidth"] = dividerWidth
		}
		if let dividerColour = dividerColour {
			data["dividerColour"] = dividerColour
		}
		if let labelColour = labelColour {
			data["labelColour"] = labelColour
		}

		return try render("divider", data: data, options: options)
	}

	/**
	 * Return empty-state output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func emptyState(
		title: String = "No results",
		detail: String = "",
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"title": title,
			"detail": detail,
		]

		return try render("empty-state", data: data, options: options)
	}

	/**
	 * Return error-block output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func errorBlock(
		title: String = "Failed",
		lines: [String]? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"title": title,
			"lines": lines ?? [],
		]

		return try render("error-block", data: data, options: options)
	}

	/**
	 * Return hint output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func hint(
		message: String,
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"message": message,
		]

		return try render("hint", data: data, options: options)
	}

	/**
	 * Return labelled-line output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func labelledLine(
		label: String = "",
		message: String = "",
		icon: String = "",
		tone: String = "info",
		wrap: Bool = true,
		wrapWidth: Int? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"label": label,
			"message": message,
			"icon": icon,
			"tone": tone,
			"wrap": wrap,
		]

		if let wrapWidth = wrapWidth {
			data["wrapWidth"] = wrapWidth
		}

		return try render("labelled-line", data: data, options: options)
	}

	/**
	 * Return next-step-block output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func nextStepBlock(
		nextStep: String,
		reason: String = "",
		command: String = "",
		alternative: String = "",
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"next": nextStep,
			"reason": reason,
			"commands": command.isEmpty ? [] : [command],
			"alternatives": alternative.isEmpty ? [] : [alternative],
		]

		return try render("next-step-block", data: data, options: options)
	}

	/**
	 * Return panel output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func panel(
		lines: [String]? = nil,
		title: String? = nil,
		tone: String = "info",
		panelWidth: Int? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"lines": lines ?? [],
			"tone": tone,
		]

		if let title = title {
			data["title"] = title
		}
		if let panelWidth = panelWidth {
			data["panelWidth"] = panelWidth
		}

		return try render("panel", data: data, options: options)
	}

	/**
	 * Return progress-bar output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func progressBar(
		max: Int = 100,
		value: Int = 0,
		barWidth: Int? = nil,
		tone: String = "success",
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"max": max,
			"value": value,
			"tone": tone,
		]

		if let barWidth = barWidth {
			data["barWidth"] = barWidth
		}

		return try render("progress-bar", data: data, options: options)
	}

	/**
	 * Return row output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func row(
		label: String,
		value: String,
		result: String = "",
		labelWidth: Int? = nil,
		labelColour: String? = nil,
		valueColour: String? = nil,
		separator: String? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"label": label,
			"value": value,
			"result": result,
		]

		if let labelWidth = labelWidth {
			data["labelWidth"] = labelWidth
		}
		if let labelColour = labelColour {
			data["labelColour"] = labelColour
		}
		if let valueColour = valueColour {
			data["valueColour"] = valueColour
		}
		if let separator = separator {
			data["separator"] = separator
		}

		return try render("row", data: data, options: options)
	}

	/**
	 * Return row-group output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func rowGroup(
		rows: [[String: Any]],
		labelWidth: Int? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"rows": rows,
		]

		if let labelWidth = labelWidth {
			data["labelWidth"] = labelWidth
		}

		return try render("row-group", data: data, options: options)
	}

	/**
	 * Return sparkline output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func sparkline(
		values: [Double]? = nil,
		width: Int? = nil,
		label: String? = nil,
		tone: String = "success",
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"values": values ?? [],
			"tone": tone,
		]

		if let width = width {
			data["width"] = width
		}
		if let label = label {
			data["label"] = label
		}

		return try render("sparkline", data: data, options: options)
	}

	/**
	 * Return span output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func span(
		value: String,
		tone: String = "info",
		weight: String? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"value": value,
			"tone": tone,
		]

		if let weight = weight {
			data["weight"] = weight
		}

		return try render("span", data: data, options: options)
	}

	/**
	 * Return status output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func status(
		type: String,
		label: String = "",
		detail: String = "",
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"type": type,
			"label": label,
			"detail": detail,
		]

		return try render("status", data: data, options: options)
	}

	/**
	 * Return step output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func step(
		label: String = "",
		state: String = "pending",
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"label": label,
			"state": state,
		]

		return try render("step", data: data, options: options)
	}

	/**
	 * Return step-progress output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func stepProgress(
		current: Int = 0,
		steps: [String]? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"current": current,
			"steps": steps ?? [],
		]

		return try render("step-progress", data: data, options: options)
	}

	/**
	 * Return table output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func table(
		columns: [[String: Any]],
		rows: [[String: Any]],
		unicode: Bool? = nil,
		width: Int? = nil,
		options: CliStyleOptions = .init()
	) throws -> String {
		var data: [String: Any] = [
			"columns": columns,
			"rows": rows,
		]

		if let unicode = unicode {
			data["unicode"] = unicode
		}
		if let width = width {
			data["width"] = width
		}

		return try render("table", data: data, options: options)
	}

	/**
	 * Return task-summary output from the cli-style binary; `options` sets the profile, width, and binary.
	 */
	public static func taskSummary(
		result: String,
		task: String,
		summary: String = "",
		completed: String = "",
		remaining: String = "",
		options: CliStyleOptions = .init()
	) throws -> String {
		let data: [String: Any] = [
			"result": result,
			"task": task,
			"summary": summary,
			"completed": completed.isEmpty ? [] : [completed],
			"remaining": remaining.isEmpty ? [] : [remaining],
		]

		return try render("task-summary", data: data, options: options)
	}

}
