# Generated by scripts/generate-adapters.js. Do not edit directly.

from __future__ import annotations

from typing import Any

from .core import render

def agent_transcript(
	entries: list[dict[str, Any]] | None = None,
	title: str | None = None,
	**kwargs: Any,
) -> str:
	"""Return agent-transcript output; extra keyword arguments go to render()."""
	data = {
		"entries": [] if entries is None else entries,
	}

	if title is not None:
		data["title"] = title

	return render("agent-transcript", data, **kwargs)


def audit_finding(
	result: str,
	finding: str,
	location: str = "",
	recommendation: str = "",
	evidence: str = "",
	reference: str = "",
	**kwargs: Any,
) -> str:
	"""Return audit-finding output; extra keyword arguments go to render()."""
	data = {
		"result": result,
		"finding": finding,
		"location": location,
		"recommendation": recommendation,
		"evidence": [evidence] if evidence else [],
		"references": [reference] if reference else [],
	}

	return render("audit-finding", data, **kwargs)


def bar_chart(
	rows: list[dict[str, Any]] | None = None,
	bar_width: int | float | None = None,
	**kwargs: Any,
) -> str:
	"""Return bar-chart output; extra keyword arguments go to render()."""
	data = {
		"rows": [] if rows is None else rows,
	}

	if bar_width is not None:
		data["barWidth"] = bar_width

	return render("bar-chart", data, **kwargs)


def bullet_list(
	items: list[dict[str, Any]],
	**kwargs: Any,
) -> str:
	"""Return bullet-list output; extra keyword arguments go to render()."""
	data = {
		"items": items,
	}

	return render("bullet-list", data, **kwargs)


def chip(
	label: str,
	tone: str = "neutral",
	**kwargs: Any,
) -> str:
	"""Return chip output; extra keyword arguments go to render()."""
	data = {
		"label": label,
		"tone": tone,
	}

	return render("chip", data, **kwargs)


def command_result(
	result: str,
	summary: str,
	command: str = "",
	exit_code: int | float | None = None,
	duration: str = "",
	detail: str = "",
	**kwargs: Any,
) -> str:
	"""Return command-result output; extra keyword arguments go to render()."""
	data = {
		"result": result,
		"summary": summary,
		"command": command,
		"duration": duration,
		"details": [detail] if detail else [],
	}

	if exit_code is not None:
		data["exitCode"] = exit_code

	return render("command-result", data, **kwargs)


def compact_data_table(
	columns: list[dict[str, Any]],
	rows: list[dict[str, Any]],
	summary: str = "",
	title: str | None = None,
	**kwargs: Any,
) -> str:
	"""Return compact-data-table output; extra keyword arguments go to render()."""
	data = {
		"columns": columns,
		"rows": rows,
		"summary": summary,
	}

	if title is not None:
		data["title"] = title

	return render("compact-data-table", data, **kwargs)


def confirmation_result(
	state: str,
	action: str,
	item: str = "",
	detail: str = "",
	**kwargs: Any,
) -> str:
	"""Return confirmation-result output; extra keyword arguments go to render()."""
	data = {
		"state": state,
		"action": action,
		"item": item,
		"detail": detail,
	}

	return render("confirmation-result", data, **kwargs)


def diagnostic_report(
	title: str | None = None,
	checks: list[dict[str, Any]] | None = None,
	findings: list[dict[str, Any]] | None = None,
	skipped_checks: list[dict[str, Any]] | None = None,
	next_actions: list[str] | None = None,
	**kwargs: Any,
) -> str:
	"""Return diagnostic-report output; extra keyword arguments go to render()."""
	data = {
		"checks": [] if checks is None else checks,
		"findings": [] if findings is None else findings,
		"skippedChecks": [] if skipped_checks is None else skipped_checks,
		"nextActions": [] if next_actions is None else next_actions,
	}

	if title is not None:
		data["title"] = title

	return render("diagnostic-report", data, **kwargs)


def diff_block(
	lines: list[dict[str, Any]] | None = None,
	path: str = "",
	title: str | None = None,
	**kwargs: Any,
) -> str:
	"""Return diff-block output; extra keyword arguments go to render()."""
	data = {
		"path": path,
	}

	if lines is not None:
		data["lines"] = lines
	if title is not None:
		data["title"] = title

	return render("diff-block", data, **kwargs)


def divider(
	label: str = "",
	divider_width: int | float | None = None,
	divider_colour: str | None = None,
	label_colour: str | None = None,
	**kwargs: Any,
) -> str:
	"""Return divider output; extra keyword arguments go to render()."""
	data = {
		"label": label,
	}

	if divider_width is not None:
		data["dividerWidth"] = divider_width
	if divider_colour is not None:
		data["dividerColour"] = divider_colour
	if label_colour is not None:
		data["labelColour"] = label_colour

	return render("divider", data, **kwargs)


def empty_state(
	title: str = "No results",
	detail: str = "",
	**kwargs: Any,
) -> str:
	"""Return empty-state output; extra keyword arguments go to render()."""
	data = {
		"title": title,
		"detail": detail,
	}

	return render("empty-state", data, **kwargs)


def error_block(
	title: str = "Failed",
	lines: list[str] | None = None,
	**kwargs: Any,
) -> str:
	"""Return error-block output; extra keyword arguments go to render()."""
	data = {
		"title": title,
		"lines": [] if lines is None else lines,
	}

	return render("error-block", data, **kwargs)


def hint(
	message: str,
	**kwargs: Any,
) -> str:
	"""Return hint output; extra keyword arguments go to render()."""
	data = {
		"message": message,
	}

	return render("hint", data, **kwargs)


def labelled_line(
	label: str = "",
	message: str = "",
	icon: str = "",
	tone: str = "info",
	wrap: bool = True,
	wrap_width: int | float | None = None,
	**kwargs: Any,
) -> str:
	"""Return labelled-line output; extra keyword arguments go to render()."""
	data = {
		"label": label,
		"message": message,
		"icon": icon,
		"tone": tone,
		"wrap": wrap,
	}

	if wrap_width is not None:
		data["wrapWidth"] = wrap_width

	return render("labelled-line", data, **kwargs)


def next_step_block(
	next_step: str,
	reason: str = "",
	command: str = "",
	alternative: str = "",
	**kwargs: Any,
) -> str:
	"""Return next-step-block output; extra keyword arguments go to render()."""
	data = {
		"next": next_step,
		"reason": reason,
		"commands": [command] if command else [],
		"alternatives": [alternative] if alternative else [],
	}

	return render("next-step-block", data, **kwargs)


def panel(
	lines: list[str] | None = None,
	title: str | None = None,
	tone: str = "info",
	width: int | float | None = None,
	**kwargs: Any,
) -> str:
	"""Return panel output; extra keyword arguments go to render()."""
	data = {
		"lines": [] if lines is None else lines,
		"tone": tone,
	}

	if title is not None:
		data["title"] = title
	if width is not None:
		data["width"] = width

	return render("panel", data, **kwargs)


def progress_bar(
	max: int | float = 100,
	value: int | float = 0,
	bar_width: int | float | None = None,
	tone: str = "success",
	**kwargs: Any,
) -> str:
	"""Return progress-bar output; extra keyword arguments go to render()."""
	data = {
		"max": max,
		"value": value,
		"tone": tone,
	}

	if bar_width is not None:
		data["barWidth"] = bar_width

	return render("progress-bar", data, **kwargs)


def row(
	label: str,
	value: str,
	result: str = "",
	label_width: int | float | None = None,
	label_colour: str | None = None,
	value_colour: str | None = None,
	separator: str | None = None,
	**kwargs: Any,
) -> str:
	"""Return row output; extra keyword arguments go to render()."""
	data = {
		"label": label,
		"value": value,
		"result": result,
	}

	if label_width is not None:
		data["labelWidth"] = label_width
	if label_colour is not None:
		data["labelColour"] = label_colour
	if value_colour is not None:
		data["valueColour"] = value_colour
	if separator is not None:
		data["separator"] = separator

	return render("row", data, **kwargs)


def row_group(
	rows: list[dict[str, Any]],
	label_width: int | float | None = None,
	**kwargs: Any,
) -> str:
	"""Return row-group output; extra keyword arguments go to render()."""
	data = {
		"rows": rows,
	}

	if label_width is not None:
		data["labelWidth"] = label_width

	return render("row-group", data, **kwargs)


def sparkline(
	values: list[int | float] | None = None,
	width: int | float | None = None,
	label: str | None = None,
	tone: str = "success",
	**kwargs: Any,
) -> str:
	"""Return sparkline output; extra keyword arguments go to render()."""
	data = {
		"values": [] if values is None else values,
		"tone": tone,
	}

	if width is not None:
		data["width"] = width
	if label is not None:
		data["label"] = label

	return render("sparkline", data, **kwargs)


def span(
	value: str,
	tone: str = "info",
	weight: str | None = None,
	**kwargs: Any,
) -> str:
	"""Return span output; extra keyword arguments go to render()."""
	data = {
		"value": value,
		"tone": tone,
	}

	if weight is not None:
		data["weight"] = weight

	return render("span", data, **kwargs)


def status(
	type: str,
	label: str = "",
	detail: str = "",
	**kwargs: Any,
) -> str:
	"""Return status output; extra keyword arguments go to render()."""
	data = {
		"type": type,
		"label": label,
		"detail": detail,
	}

	return render("status", data, **kwargs)


def step(
	label: str = "",
	state: str = "pending",
	**kwargs: Any,
) -> str:
	"""Return step output; extra keyword arguments go to render()."""
	data = {
		"label": label,
		"state": state,
	}

	return render("step", data, **kwargs)


def step_progress(
	current: int | float = 0,
	steps: list[str] | None = None,
	**kwargs: Any,
) -> str:
	"""Return step-progress output; extra keyword arguments go to render()."""
	data = {
		"current": current,
		"steps": [] if steps is None else steps,
	}

	return render("step-progress", data, **kwargs)


def table(
	columns: list[dict[str, Any]],
	rows: list[dict[str, Any]],
	unicode: bool | None = None,
	width: int | float | None = None,
	**kwargs: Any,
) -> str:
	"""Return table output; extra keyword arguments go to render()."""
	data = {
		"columns": columns,
		"rows": rows,
	}

	if unicode is not None:
		data["unicode"] = unicode
	if width is not None:
		data["width"] = width

	return render("table", data, **kwargs)


def task_summary(
	result: str,
	task: str,
	summary: str = "",
	completed: str = "",
	remaining: str = "",
	**kwargs: Any,
) -> str:
	"""Return task-summary output; extra keyword arguments go to render()."""
	data = {
		"result": result,
		"task": task,
		"summary": summary,
		"completed": [completed] if completed else [],
		"remaining": [remaining] if remaining else [],
	}

	return render("task-summary", data, **kwargs)
